### register user
POST http://localhost:3002/registerUser
Content-Type: application/json

{
  "name":"Ben Ten",
  "email":"adam@test.com",
  "password":"adam123",
  "isAdmin":true
}

### user login, generate access token & refresh token
POST http://localhost:3002/login
Content-Type: application/json

{
    "email":"adam@test.com",
    "password":"adam123"
}

### generate new access token using provided refresh token during login
POST http://localhost:3002/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW1AdGVzdC5jb20iLCJpYXQiOjE2NzgwODQyMTd9.4G5v4Z-bey733CPqUaiHF2kA8p8LISPjAl7946lLAmQ",
  "userID": "lewce26s-dfafe5"

}

### logout, delete refresh token provided during login
DELETE  http://localhost:3002/logout
Content-Type: application/json

{
  "id": "lewce26s-dfafe5"
}

### fetch posts
POST  http://localhost:3002/fetchFiles
Authorization: Bearer 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbnkiOiJsZXpha2VhZi12NXV5aDMiLCJpYXQiOjE2NzgyNTkxNTF9.nGSn3B__1bKX_qHRiwjr7AV5JxYS9mXTakJIasIcOmw'

