### register user
POST http://localhost:3002/registerUser
Content-Type: application/json

{
  "name":"El Lephant",
  "email":"el@test.com",
  "password":"el123",
  "isAdmin":0
}

### user login
GET http://localhost:3002/login
Content-Type: application/json

{
    "email":"el@test.com",
    "password":"el123"
}