FROM node:16 as development

WORKDIR /usr/src/app

COPY ./package*.json ./

RUN npm install

COPY ./ ./

RUN npm run build

FROM node:16 as production

WORKDIR /usr/src/app

COPY ./package*.json ./

RUN npm install

COPY --from=development /usr/src/app/dist ./dist

CMD ["node","dist/index.js"]